Repository gomods/athens, pull requests merged in 2018-08, with the labels that each got.

#363 Run E2E tests during CI
  .travis.yml
  CONTRIBUTING.md
  Makefile
  scripts/get_dev_tools.sh
  scripts/test_e2e.sh
Labels: testing

#424 Docs First of many: Communication flow
  CONTRIBUTING.md
  README.md
  docs/content/_index.md
  docs/content/design/communication.md
  docs/content/design/proxy.md
  docs/content/design/registry.md
  docs/content/intro/components.md
  docs/content/intro/first-content.md
  docs/content/intro/protocol.md
  docs/static/athens-clear-scenario.png
  docs/static/athens-new-proxy-old-olympus-scenario.png
  docs/static/athens-private-repo-scenario.png
  docs/static/athens-proxy-filled.png
Labels: docs

#410 Fix up e2e script
  .travis.yml
  scripts/get_dev_tools.sh
  scripts/test_e2e.sh
Labels: ci/cd

#426 Benchmark storages
  Makefile
  pkg/config/env/mongo.go
  pkg/storage/fs/test_suite.go
  pkg/storage/mem/test_suite.go
  pkg/storage/minio/test_suite.go
  pkg/storage/mongo/mongo.go
  pkg/storage/mongo/test_suite.go
  pkg/storage/rdbms/test_suite.go
  pkg/storage/storage_tests/module_storage/storage_benchmark_test.go
  pkg/storage/test_suite.go
  scripts/benchmark.sh
Labels: storage

#443 Changing gophers slack link to be the invite link
  CONTRIBUTING.md
Labels: docs

#454 adding a docker build target for the proxy
  Makefile
Labels: ci/cd, dev ux

#477 Update e2e tests to not use sudo
  scripts/test_e2e.sh
Labels: dev ux

#493 Update the doc site index to include try it out langauge
  docs/content/_index.md
Labels: docs

#544 Deploy docker image during CI
  .travis.yml
  Makefile
  scripts/push-docker-images.sh
Labels: do not merge

#525 Powershell scripts
  init.ps1
  scripts/ps/benchmark.ps1
  scripts/ps/check_gofmt.ps1
  scripts/ps/check_golint.ps1
  scripts/ps/get_dev_tools.ps1
  scripts/ps/test_e2e.ps1
  scripts/ps/test_unit.ps1
Labels: dev ux

#470 adding document that explains how reviews happen on PRs
  CONTRIBUTING.md
  DEVELOPMENT.md
  REVIEWS.md
Labels: docs

#371 Add support for Go Modules
  go.mod
  go.sum
Labels: blocked

#565 disable inline copy to clipboard
  docs/config.toml
Labels: docs

#543 How to install a shared dev team instance with persistent storage
  docs/content/install/shared-team-instance.md
  docs/content/walkthrough.md
Labels: blocked, docs

#569 No conflicts
  Makefile
  scripts/check_conflicts.sh
Labels: ci/cd, dev ux

#585 Added ISSUE and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: community, dev ux
