Repository gomods/athens, pull requests merged in 2018-07, with the labels that each got.

#227 WIP: Removing the CLI
  cmd/cli/main.go
  cmd/cli/upload.go
  cmd/cli/usage.go
  cmd/proxy/actions/app_proxy.go
  cmd/proxy/actions/upload.go
  pkg/payloads/upload.go
Labels: cli, docs

#230 WIP: always downloading a fixed buffalo CLI version
  .travis.yml
  scripts/get_buffalo.sh
Labels: ci/cd

#236 Adding getting involved section, resources, etc...
  README.md
Labels: docs

#246 Adding an athens philosophy document
  PHILOSOPHY.md
  README.md
Labels: docs

#272 Zeus: remove duplicate '/' handler assignment
  cmd/proxy/actions/app.go
  cmd/proxy/actions/home.go
Labels: bug, proxy

#264 CDN parallel uploads
  pkg/storage/azurecdn/storage.go
  pkg/storage/gcp/bucket.go
  pkg/storage/gcp/bucket_cloud.go
  pkg/storage/gcp/checker.go
  pkg/storage/gcp/deleter.go
  pkg/storage/gcp/getter.go
  pkg/storage/gcp/lister.go
  pkg/storage/gcp/saver.go
  pkg/storage/module/delete.go
  pkg/storage/module/delete_test.go
  pkg/storage/module/upload.go
  pkg/storage/module/upload_test.go
  pkg/storage/s3/storage.go
Labels: storage

#313 Adding registry build to the makefile
  Makefile
Labels: refactor

#291 Moving the fetch logic into 'pkg/module'
  .travis.yml
  Gopkg.lock
  pkg/errors/errors.go
  pkg/module/all_test.go
  pkg/module/disk_ref.go
  pkg/module/disk_ref_test.go
  pkg/module/errors.go
  pkg/module/fetch.go
  pkg/module/fetcher.go
  pkg/module/go_get_fetcher.go
  pkg/module/go_get_fetcher_test.go
  pkg/module/noop_ref.go
  pkg/module/ref.go
  pkg/repo/WARNING.md
Labels: refactor

#323 Specify mysql should be installed as part of development bootstrap
  DEVELOPMENT.md
Labels: dev ux, on hold, question

#338 Finish spans in the download handlers
  pkg/download/list.go
  pkg/download/version_info.go
  pkg/download/version_module.go
  pkg/download/version_zip.go
Labels: bug

#352 Cleaning up unused code
  cmd/olympus/actions/app.go
  cmd/olympus/actions/package_downloader.go
  cmd/proxy/actions/app_proxy.go
  cmd/proxy/actions/fetch.go
  pkg/gomod/bytes/parser.go
  pkg/gomod/bytes/parser_test.go
  pkg/gomod/file/parser.go
  pkg/gomod/file/parser_test.go
  pkg/gomod/file/testdata/go.0.mod
  pkg/gomod/file/testdata/go.1.mod
  pkg/gomod/file/testdata/go.2.mod
  pkg/gomod/file/testdata/go.3.mod
  pkg/gomod/file/testdata/go.4.mod
  pkg/gomod/parser.go
  pkg/gomod/parser_test.go
  pkg/gomod/zip/parser.go
  pkg/gomod/zip/parser_test.go
  pkg/gomod/zip/testdata/Gopkg.toml
  pkg/gomod/zip/testdata/go.0.mod
  pkg/gomod/zip/testdata/go.1.mod
  pkg/gomod/zip/testdata/go.2.mod
  pkg/gomod/zip/testdata/go.3.mod
  pkg/gomod/zip/testdata/go.4.mod
  pkg/repo/WARNING.md
  pkg/repo/fetcher.go
  pkg/repo/github/commitinfo.go
  pkg/repo/github/github.go
  pkg/repo/github/github_test.go
  pkg/repo/goget.go
  pkg/repo/goget_test.go
Labels: proxy, refactor, registry
