Repository gomods/athens, pull requests merged in 2018-11, with the labels that each got.

#860 Config cleanup
  cmd/proxy/actions/storage.go
  pkg/config/azure.go
  pkg/config/cdn.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/storage.go
  pkg/storage/azurecdn/blob_store_client.go
  pkg/storage/azurecdn/storage.go
  pkg/storage/gcp/all_test.go
  pkg/storage/gcp/gcp.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
Labels: refactor

#900 Fix docker builds in Travis
  cmd/proxy/Dockerfile
Labels: awaiting review

#889 Checking the number of bytes written to Mongo GridFS
  pkg/storage/mongo/saver.go
Labels: bug

#908 cmd/proxy: add /version endpoint to probe the server version
  cmd/proxy/actions/app_proxy.go
  cmd/proxy/actions/version.go
Labels: Frozen

#920 pass custom timestamp format to the log formatter
  pkg/log/log_test.go
Labels: testing

#956 changing the zoom link to a shortlink
  docs/content/contributing/community/developer-meetings.md
Labels: docs

#957 Maint resources
  MAINTAINER_RESOURCES.md
Labels: community, docs
