Repository gomods/athens, pull requests merged in 2018-09, with the labels that each got.

#468 Tiny start to the codeowners file
  .github/CODEOWNERS
Labels: community

#621 change go releaser to create draft releases
  .goreleaser.yml
Labels: community, proposal

#648 Fix for Windows 10
  init.ps1
  pkg/module/go_get_fetcher.go
  scripts/ps/create_default_config.ps1
  scripts/ps/test_e2e.ps1
Labels: awaiting review

#649 Fix end 2 end test
  scripts/test_e2e.sh
Labels: awaiting review

#607 Fix list
  cmd/olympus/actions/app.go
  cmd/proxy/actions/app_proxy.go
  pkg/download/list_merge_test.go
  pkg/download/protocol.go
  pkg/download/protocol_test.go
  pkg/download/upstream_lister.go
  pkg/errors/gocmd.go
  pkg/storage/fs/lister.go
  pkg/storage/gcp/gcp_test.go
  pkg/storage/gcp/lister.go
  pkg/storage/minio/lister.go
  pkg/storage/mongo/lister.go
  pkg/storage/storage_tests/module_storage/storage_test.go
Labels: awaiting review

#663 redirect other domain requests to docs.gomods.io
  netlify.toml
Labels: awaiting review

#662 Adding CodeTriage badge
  README.md
Labels: community, docs

#614 Clean up error operation names to match function names.
  pkg/download/version_info.go
  pkg/middleware/filter.go
  pkg/middleware/validation.go
  pkg/module/disk_ref.go
Labels: awaiting review

#661 Adding comments on when to use each review type
  REVIEWS.md
Labels: docs

#570 docs: contribution guides
  docs/content/contributing/_index.md
  docs/content/contributing/community-roles.md
  docs/content/contributing/maintainers/_index.md
  docs/content/contributing/maintainers/first-issues.md
  docs/content/contributing/new/_index.md
  docs/content/contributing/new/git.md
  docs/content/contributing/new/github.md
  docs/content/design/_index.md
  docs/content/install/_index.md
  docs/content/intro/_index.md
  docs/static/github-issue-header.png
  docs/static/github-issue-templates.png
Labels: awaiting review, community, dev ux, docs
