Repository gomods/athens, pull requests merged in 2020-03, with the labels that each got.

#1554 Adds redis sentinel support
  .drone.yml
  cmd/proxy/actions/app_proxy.go
  config.dev.toml
  docker-compose.yml
  docs/content/configuration/storage.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/singleflight.go
  pkg/stash/with_redis.go
  pkg/stash/with_redis_sentinel.go
  pkg/stash/with_redis_sentinel_test.go
Labels: enhancement, hosting

#1566 Fixing code like the go team printed version link
  README.md
Labels: bug, docs

#1576 Adding notes for how to do a release
  DEVELOPMENT.md
Labels: docs
