Repository gomods/athens, pull requests merged in 2024-04, with the labels that each got.

#1934 Upgrade logrus from 1.7.0 => 1.9.3
  go.mod
  go.sum
Labels: security

#1936 should use errors.AsErr to extract and detect errors.Error
  pkg/log/entry.go
Labels: bug

#1952 Add logging configuration docs
  docs/content/configuration/logging.md
Labels: docs

#1950 Upgrade to AWS SDK v2 (#1938)
  .github/workflows/ci.yml
  cmd/proxy/actions/app_proxy_test.go
  cmd/proxy/actions/index_test.go
  cmd/proxy/actions/storage.go
  docker-compose.yml
  e2etests/all_test.go
  go.mod
  go.sum
  pkg/config/azureblob.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/disk.go
  pkg/config/external.go
  pkg/config/gcp.go
  pkg/config/minio.go
  pkg/config/mongo.go
  pkg/config/mysql.go
  pkg/config/postgres.go
  pkg/config/s3.go
  pkg/download/list_merge_test.go
  pkg/download/mode/mode_test.go
  pkg/download/protocol_test.go
  pkg/middleware/middleware_test.go
  pkg/module/filter_test.go
  pkg/storage/minio/minio.go
  pkg/storage/minio/minio_test.go
  pkg/storage/mongo/mongo_test.go
  pkg/storage/s3/cataloger.go
  pkg/storage/s3/checker.go
  pkg/storage/s3/deleter.go
  pkg/storage/s3/getter.go
  pkg/storage/s3/lister.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/s3/saver.go
  scripts/ps/test_unit.ps1
  scripts/test_unit.sh
Labels: dependencies
